name: Run Docker on Multiple Platforms

on:
  workflow_dispatch:

jobs:
  run-docker-linux:
    name: Linux
    runs-on: ubuntu-24.04
    steps:
      - name: Run Geekbench Container
        run: docker run davidmatthews/geekbench:latest

  run-docker-linux-arm:
    name: Linux (ARM)
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Run Geekbench Container
        run: docker run davidmatthews/geekbench:latest

  run-docker-macos:
    name: macOS
    runs-on: macos-13
    steps:
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install Colima and Docker CLI
        run: |
          brew install colima docker
  
      - name: Start Colima
        run: |
          colima start --cpu 4 --memory 8

      - name: Run Geekbench Container
        run: docker run davidmatthews/geekbench:latest

      - name: Check Colima Logs on Failure
        if: failure()
        run: |
          cat /Users/runner/.colima/_lima/colima/ha.stderr.log || echo "No logs found"
          cat /Users/runner/.colima/_lima/colima/serial*.log || echo "No logs found"