name: Run Docker on Multiple Platforms

on:
  workflow_dispatch:

jobs:
  run-docker-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Run Geekbench Container
        run: docker run davidmatthews/geekbench:latest

  run-docker-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Run Geekbench Container
        run: docker run davidmatthews/geekbench:latest

  run-docker-macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install Docker
        run: |
          brew install --cask docker
          open /Applications/Docker.app
          sleep 15  # Allow time for Docker to initialize

      - name: Verify Docker installation
        run: docker --version

      - name: Run Geekbench Container
        run: docker run davidmatthews/geekbench:latest