name: Run Docker on Multiple Platforms

on:
  workflow_dispatch:

jobs:
  run-docker-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Run Geekbench Container
        run: docker run davidmatthews/geekbench:latest

  run-docker-macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install Colima and Docker CLI
        run: |
          brew install colima docker
  
      - name: Start Colima
        run: |
          colima start

      - name: Run Geekbench Container
        run: docker run davidmatthews/geekbench:latest